# Generated by Django 4.2.5 on 2023-09-22 21:58

from django.db import migrations, models
import django.db.models.deletion

def criar_contas_bancarias(apps, schema_editor):
    conta_bancaria = apps.get_model('financeiro', 'ContaBancaria')
    conta_bancaria.objects.create(
        titular='João',
        saldo=1000,
        tipo_conta='corrente'
    )
    conta_bancaria.objects.create(
        titular='João',
        saldo=1,
        tipo_conta='poupanca'
    )
    conta_bancaria.objects.create(
        titular='Maria',
        saldo=1,
        tipo_conta='poupanca'
    )

def criar_extratos(apps, schema_editor):
    extrato = apps.get_model('financeiro', 'Extrato')
    extrato.objects.create(
        conta_id=1,
        data='2023-09-22',
        descricao='Salário',
    )
    extrato.objects.create(
        conta_id=2,
        data='2023-09-22',
        descricao='Poupança',
    )
    
    
class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titular", models.CharField(max_length=100)),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo_conta",
                    models.CharField(
                        choices=[
                            ("corrente", "Conta Corrente"),
                            ("poupanca", "Conta Poupança"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
                "db_table": "conta_bancaria",
            },
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "conta_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes_destino",
                        to="financeiro.contabancaria",
                    ),
                ),
                (
                    "conta_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes_origem",
                        to="financeiro.contabancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
            },
        ),
        migrations.CreateModel(
            name="Extrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("descricao", models.CharField(max_length=255)),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeiro.contabancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extrato",
                "verbose_name_plural": "Extratos",
                "db_table": "extrato",
            },
        ),
        migrations.RunPython(criar_contas_bancarias),
        migrations.RunPython(criar_extratos),
    ]
